### ISSUE TITLE
Changing Data Source from SDE to GDB

### ISSUE THREAD

**Issue by AndrewBuiltThis** [DavidWhittingham/arcpyext#15]
Hey David!

Love your repos -- looks like we're tackling a lot of the same work from different angles (I'm a Node fella). 

I haven't been able to change a .sddraft's data source from an enterprise database (.sde connection) to a file geodatabase (gdb) and was unsure if this was possible with your library. Have you been able to accomplish this? 

Back story: users connect to an Oracle Enterprise Geodatabase. Servers use local, synced replicas of the data on file geodatabases. 

Any samples / suggestions would be much appreciated!

**Comment by DavidWhittingham** [comment]
Hi Andrew,

I don't believe this is possible from the SD Draft.  SD Drafts collect all the server side settings, but they don't collect much about the source data.  In the case of a Map Document (*.mxd), they only include a link to the document.  This is why, your best bet is to alter what each layer is pointing to in the client (ArcMap for Map Documents, ArcGIS Pro for Projects) before publishing.

`arcpyext` includes functionality to help with that goal, but it only works by modifying the source document, not the SD Draft, and is completely dependent on a licened install of ArcGIS Desktop or ArcGIS Server.  I can give examples/update the readme if you're interested in pursuing this path.  Note, it doesn't support ArcGIS Pro in the release build yet, but myself and a couple others have been doing work towards this, and that is getting close to finished.

**Comment by AndrewBuiltThis** [comment]
That ould be awesome if you could provide an example and/or update the readMe with samples. I'll be sure to fork the repo an add my methods as well!

**Comment by DavidWhittingham** [comment]
Hi @AndrewBuiltThis,

I just wanted to let you that I haven't forgotten about this.  We've been working on a major release to `arcpyext`, and it's consuming most of my time at the moment.  I don't want to add anything until it's ready, because there are breaking changes between the releases.  Bear with me, it hopefully won't be too much longer.

**Comment by DavidWhittingham** [comment]
Hi @AndrewBuiltThis,

I've updated the main readme file with more information and examples.  These updates only apploy to the version that's currently in development, which will be a major update, but as stated previously it's pretty close to release (I'm hoping we're happy with the stability of it this week).  Have a read, let me know if things don't make sense or if more detail is required in one area or another.
